### ISSUE TITLE
[1.15.2] Mana trait not repairing

### ISSUE THREAD

**Issue by mr-poyo** [Partonetrain/managear#2] opened 2020-07-03 04:46 UTC
Hello,

managear-1.1.1.jar
SilentGear-1.15.2-1.8.1+108.jar
SilentLib-1.15.2-4.6.4+56.jar
Forge: 31.2.20

A player on my server is using terrasteel and elementium as materials for his silent gear, and it seems the mana repair trait isn't working at all. He was able to create his silent gear, and the gear drains mana as you would expect, but the gear isn't repairing. Thank you!

**Comment by Partonetrain** [comment] 2020-07-29 23:01
Apologies for super late reply. I did test this when it was reported but was never able to reproduce. Is this still happening? I'd need more information to fix it

**Comment by MokahTGS** [comment] 2020-07-31 19:46
yeah, we are seeing this as well.

**Comment by Partonetrain** [comment] 2020-08-01 02:03
Still not able to reproduce. Can I get more details, like what type of gear? I've tested it with a sword, pickaxe, and hammer, and all work fine in my dev environment.

**Comment by MokahTGS** [comment] 2020-08-01 05:22
I've tried it with pickaxe, shovel, hammer, axe, and machete.

**Comment by MokahTGS** [comment] 2020-08-01 14:46
This is our mod list for our server:  https://pastebin.com/RwV3trHe

It's a modified version of the Valhelsia 2 modpack for 1.15.2

**Comment by Partonetrain** [comment] 2020-08-01 16:32
Valhesia 2 adds its own Botania material via datapack, and does not have ManaGear natively. This could be causing a conflict. Delete the materials in ```Valhelsia 2\openloader\data\Valhelsia-SilentGear\data\silentgear\silentgear_parts\main``` to guarantee the use of the ManaGear variants.

That said, I _still_ can't reproduce this, even with the duplicate materials and the mod list your provided, as seen here:
https://cdn.discordapp.com/attachments/176021701094670336/739157819063926784/2020-08-01_11-27-51.mp4

**Comment by MokahTGS** [comment] 2020-08-01 19:26
Confirmed for me.  Taking out the Valhelsia mana traits from the data pack has fixed the issue on our server.

**Comment by Partonetrain** [comment] 2020-08-13 02:38
SGear now notifies the user of duplicate material entries, so I'm closing this

**Closed as completed by Partonetrain** 2020-08-13 02:38 UTC
Labels: invalid
